// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// Load .env.local first (takes precedence), then .env as fallback.
config({ path: ".env.local" });
config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspection run over a direct connection (port 5432), not the
    // transaction pooler. Falls back to DATABASE_URL for local single-URL setups.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
